### PR TITLE
Make it so Backups can be prefixed by the container name.

### LINKED ISSUE #63: [Suggestion] Write backup file in a sub directory
Hi I ran into an issue when backing up multiple bedrock servers that have the same world name. For example,
```
Container A
  server_name: BedrockServer1
    level_name: Survival
Container B
  server_name: BedrockServer2
    level_name: Survival
```
The backup files generated can conflict if the backup happens quickly. My suggestion would be to put the backup file in a sub directory. So with the example above the backup would look like:
```
/opt/bedrock/backups/BedrockServer1/Survival.timestamp.mcworld
/opt/bedrock/backups/BedrockServer2/Survival.timestamp.mcworld
```
or prepend with the server name
```
/opt/bedrock/backups/BedrockServer1.Survival.timestamp.mcworld
/opt/bedrock/backups/BedrockServer2.Survival.timestamp.mcworld
```
Of course you would still run into the same problem if the server names were not unique. Not sure if the container name could be used instead since those are required to be unique.

Thank you for this project!

### PR DESCRIPTION
**Pull request by Kaiede**
Resolves #63

### CODE REVIEW

**Comment by rveachkc** [comment]
Hey, I love your work here.  ...but I spent a lot of my day troubleshooting some weird bedrock level-name issues.

It would be super helpful to have a release made that included this PR.  I see `test` is out there, but I'd feel better if there was another tag that didn't track on your main branch.

Thanks!

**Comment by Kaiede** [comment]
> It would be super helpful to have a release made that included this PR. I see `test` is out there, but I'd feel better if there was another tag that didn't track on your main branch.

Unfortunately, this was something I've wanted to get out for a while, but there's a couple of changes I need to wrap up before I could tag a new release. To make matters more complicated, personal matters have flipped the table on me in the last few months, so I haven't had as much time as I'd like. But I'll see what I can do to wrap up work on the next release.

**Comment by rveachkc** [comment]
I hear that, and wish you the best!  If I knew swift, I'd try to jump in and help, but I fear I might do more harm than good.

**Comment by Kaiede** [comment]
This is now part of 1.4.0 and latest.

**Pull request merged**
